name: Features

on:
  push:
    branches:
      - "dev"
  pull_request:
    branches:
      - "dev"


jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: restclg
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean install

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: artifact-file-jar
          path: target/*.jar

  deploy:

    needs: build
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: artifact-file-jar

      - name: Deploy to AWS EB
        uses: einaregilsson/beanstalk-deploy@6f594ded1b0a22c5e5aa1088e7c58dc5816c92ea
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          use_existing_version_if_available: false
          application_name: spring-boot-react-github-actions-aws
          environment_name: Springbootreactgithubactionsaws-env
          version_label: ${{github.SHA}}
          region: ap-south-1
          deployment_package: Rest-service-Clg-0.0.1-SNAPSHOT.jar